from __future__ import annotations

import subprocess
import threading
import time
from pathlib import Path
from shutil import which
from typing import Optional

from .logging import get_logger


def mediamtx_path() -> Optional[str]:
    return which("mediamtx") or which("rtsp-simple-server")


def start_mediamtx(rtsp_port: int, *, bind_host: str = "0.0.0.0") -> tuple[subprocess.Popen, Path]:
    exe = mediamtx_path()
    if exe is None:
        raise RuntimeError("MediamTX not found on PATH")

    logs_dir = Path("logs")
    logs_dir.mkdir(parents=True, exist_ok=True)

    cfg_path = logs_dir / "mediamtx.yml"

    # Minimal config for MediamTX v1.15.x.
    # Allow publishing/reading any path by using authInternalUsers with user:any.
    cfg_path.write_text(
        (
            """# Auto-generated by mock_nvr
logLevel: info
logDestinations: [stdout]
logStructured: no

rtsp: yes
rtspAddress: {bind_host}:{port}
rtspTransports: [tcp, udp]

rtmp: no
hls: no
webrtc: no
srt: no

authMethod: internal
authInternalUsers:
- user: any
  pass:
  ips: []
  permissions:
  - action: publish
    path:
  - action: read
    path:

# Allow any path to be published by ffmpeg and read by clients.
paths:
    "~^.*$":
        source: publisher
"""
        ).format(port=rtsp_port, bind_host=bind_host)
    )

    proc = subprocess.Popen([exe, str(cfg_path)], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)

    stdout = proc.stdout
    if stdout is not None:
        log = get_logger().bind(source="mediamtx")

        def _reader():
            for raw in iter(stdout.readline, b""):
                try:
                    line = raw.decode("utf-8", errors="replace").rstrip()
                except Exception:
                    line = repr(raw)
                if line:
                    log.info("mediamtx", line=line)

        t = threading.Thread(target=_reader, name="mediamtx-log-reader", daemon=True)
        t.start()

    # Give it a moment to bind.
    time.sleep(0.2)
    return proc, cfg_path
